### Dev konfigurasjon

# Database konfigurasjon
spring.datasource.driver-class-name        = org.h2.Driver
spring.datasource.generate-unique-name     = false
spring.datasource.name                     = testdb
spring.datasource.username                 = sa
spring.datasource.password                 =
spring.datasource.url                      = jdbc:h2:mem:testdb

# JPA konfigurasjon
spring.jpa.database                        = H2
spring.jpa.hibernate.ddl-auto              = update
# Trenger ikke show-sql her fordi sql log level er DEBUG
spring.jpa.show-sql                        = false
spring.jpa.open-in-view                    = true
spring.jpa.properties.hibernate.format_sql = false

# H2 konfigurasjon
spring.h2.console.enabled                  = true
spring.h2.console.path                     = /h2-console

# Logging
logging.level.root                         = INFO
logging.level.no.hvl.peristeri             = DEBUG
logging.level.org.springframework.web      = DEBUG
logging.level.org.hibernate.SQL            = DEBUG
logging.level.sql                          = DEBUG
logging.level.web                          = DEBUG
logging.level.org.springframework.security = DEBUG

# Disable caching for templates
spring.thymeleaf.cache                     = false

# Actuator configuration for dev
management.endpoints.web.exposure.include  = *
management.endpoint.health.show-details    = always

# DevTools (already implicitly enabled in dev environment)
spring.devtools.restart.enabled            = true
spring.devtools.livereload.enabled         = true
