### Enable this profile for postgresql

# Postgres database
spring.datasource.driver-class-name    = org.postgresql.Driver
spring.datasource.url                  = jdbc:postgresql://postgres:5432/peristeri
spring.datasource.username             = peristeri
spring.datasource.password             = peristeri_password
spring.datasource.generate-unique-name = false
spring.datasource.name                 = peristeri

# JPA konfigurasjon
spring.jpa.database                    = Postgresql
