### Felles konfigurasjon for alle profiler

# Generell app konfigurasjon
spring.application.name                    = Peristeri
server.port                                = 8181
server.servlet.context-path                = /

# Thymeleaf konfigurasjon
spring.thymeleaf.mode                      = HTML
spring.thymeleaf.prefix                    = classpath:/templates/
spring.thymeleaf.suffix                    = .html
spring.thymeleaf.enable-spring-el-compiler = true

# Tegnsett
server.servlet.encoding.charset            = UTF-8
server.servlet.encoding.enabled            = true
server.servlet.encoding.force              = true

# https forward headers
server.forward-headers-strategy            = native

# Default profil (overstyres via cmdline flag (-Dspring.profiles.active=), env variabel (SPRING_PROFILES_ACTIVE=), intellij run config)
spring.profiles.active                     = dev

# For å lage en default admin bruker
# eller bruk cmdline flag (-Dapp.admin.email=, -Dapp.admin.name=, -Dapp.admin.password=)
# eller env variabler (APP_ADMIN_EMAIL=, APP_ADMIN_NAME=, APP_ADMIN_PASSWORD=)
#app.admin.email                  =
#app.admin.name                   =
#app.admin.password               =
