### Profil for demo, inneholder for det meste det samme som dev, med mindre logging

# Database konfigurasjon
spring.datasource.driver-class-name           = org.h2.Driver
spring.datasource.generate-unique-name        = false
spring.datasource.name                        = testdb
spring.datasource.username                    = sa
spring.datasource.password                    =
spring.datasource.url                         = jdbc:h2:mem:testdb

# JPA konfigurasjon
spring.jpa.database                           = H2
spring.jpa.hibernate.ddl-auto                 = update
spring.jpa.show-sql                           = false
spring.jpa.open-in-view                       = true
spring.jpa.properties.hibernate.format_sql    = false

# H2 konfigurasjon
spring.h2.console.enabled                     = false

# Logging
logging.level.root                            = INFO
logging.level.no.hvl.peristeri                = INFO
logging.level.org.springframework.web         = INFO
logging.level.org.hibernate.SQL               = INFO

# Disable caching for templates
spring.thymeleaf.cache                        = false

# Ikke vis stacktrace på nettside hvis app kræsjer
server.error.include-stacktrace               = never
server.error.include-message                  = never
server.error.include-binding-errors           = never

# Actuator configuration for demo
management.endpoints.web.exposure.include     = health,info,metrics
management.endpoint.health.show-details       = when_authorized
management.endpoint.health.probes.enabled     = true

# Basic security for actuator endpoints
management.endpoints.web.cors.allowed-origins = *
management.endpoints.web.cors.allowed-methods = GET

# Disable DevTools
spring.devtools.restart.enabled               = false
spring.devtools.livereload.enabled            = false
spring.devtools.add-properties                = false
