-- Queries for å verifiserer burnummer generering er likt som sortering
SELECT d.ID, d.BURNUMMER, CONCAT(r.NAVN, ' (', r.GRUPPE, ')') AS RASE
FROM DUE d
LEFT JOIN RASE r ON d.RASE_ID = r.ID
WHERE d.BURNUMMER IS NOT NULL
ORDER BY d.BURNUMMER;
SELECT u.ID, u.RASE_SORTERING FROM UTSTILLING u WHERE u.RASE_SORTERING IS NOT NULL;
